services:
  postgres:
    image: postgres:14
    restart: always
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=looply-local
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  azure-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    volumes:
      - ./.containers/blob_storage/data:/data
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 --blobPort 10000 -l /data"
volumes:
  db: 